# Generated by Django 6.0.2 on 2026-03-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0002_disparity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="disparitys",
            field=models.ManyToManyField(blank=True, to="store.disparity"),
        ),
    ]
